import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { api } from '~/utils/api';

const Home: NextPage = () => {
  const newGame = api.ticTacToe.startNewGame.useMutation();
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
                        <button
                            onClick={() => newGame.mutate()}
                            disabled={ !newGame.isIdle }
                            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                        >
                            <h3 className="text-2xl font-bold">Create A New Game!</h3>
                        </button>
                        { newGame.isSuccess &&
                        <Link
                            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                            href= { `ticTacToe/${newGame.data.gameId}`}
                            target="_blank"
                        >
                            <h3 className="text-2xl font-bold">
                               Go to game 
                            </h3>
                        </Link> }
                    </div>
                </div>
            </main>
        </>
    );
};

export default Home;
